### ISSUE TITLE
ERROR: Unknown variable "has_xfs_deps".

### ISSUE THREAD

**Issue by pm-McFly** [franko/fox-1.6#1]
Hi,

just trying to compile and install the code and the first command:
```
$> meson build
```
failed with the message: Unknown variable "has_xfs_deps".

It seems (thanks to logs) that there is a typo at line 124 of `meson.build`.
"has_xfs_deps" should be "has_xft_deps".

**Comment by franko** [comment]
Wow, my first issue on this repository! Thank you for reporting that.

**Comment by pm-McFly** [comment]
Ahah !

It's better to have none, but glad to help.
Thanks, and congrats, for your response time by the way.

Le mar. 23 mars 2021 6 h 05 p.m., Francesco ***@***.***> a
écrit :
